const wordList = [
  { word: "applicant", meaning: "지원자, 신청자" },
  { word: "custody", meaning: "감금, 구류" },
  { word: "associate", meaning: "관련시키다" },
  { word: "effect", meaning: "효과, 영향" },
  { word: "candidate", meaning: "후보자, 지원자" },
  { word: "enforce", meaning: "시행하다" },
  { word: "certification", meaning: "증명서" },
  { word: "exception", meaning: "예외" },
  { word: "confidence", meaning: "확신, 자신감" },
  { word: "degree", meaning: "학위" },
  { word: "eligible", meaning: "자격이 있는" },
  { word: "employment", meaning: "고용" },
  { word: "entitle", meaning: "~에게 자격을 주다" },
  { word: "meet", meaning: "만족시키다" },
  { word: "occupation", meaning: "직업" },
  { word: "paycheck", meaning: "급료, 지불" },
  { word: "payroll", meaning: "급료명부" },
  { word: "professional", meaning: "직업의" },
  { word: "proficiency", meaning: "능숙, 숙달" },
  { word: "prospective", meaning: "미래의" },
  { word: "reference", meaning: "추천서, 참고" },
  { word: "recruit", meaning: "모집하다" },
  { word: "qualified", meaning: "자격 있는" },
  { word: "resume", meaning: "이력서" },
  { word: "requirement", meaning: "필요조건" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "access", meaning: "접근" },
  { word: "according to", meaning: "~에 따라" },
  { word: "accuse", meaning: "비난하다" },
  { word: "approval", meaning: "승인, 인가" },
  { word: "at all times", meaning: "항상, 언제나" },
  { word: "attorney", meaning: "변호사" },
  { word: "authorize", meaning: "~을 인가하다" },
  { word: "comply with", meaning: "~따르다" },
  { word: "concerned", meaning: "염려하는" },
  { word: "confront", meaning: "~에 직면하다" },
  { word: "contemporary", meaning: "현대의" },
  { word: "contradict", meaning: "모순되다" },
  { word: "contrary", meaning: "반대" },
  { word: "contribute", meaning: "기여하다" },
  { word: "dedicate", meaning: "헌신하다" },
  { word: "defend", meaning: "방어하다" },
  { word: "delegate", meaning: "대표자" },
  { word: "deliver", meaning: "전달하다" },
  { word: "demonstrate", meaning: "증명하다" },
  { word: "desire", meaning: "욕구, 소망" },
  { word: "diligent", meaning: "근면한" },
  { word: "dispute", meaning: "논쟁, 분쟁" },
  { word: "distinct", meaning: "구별되는" },
  { word: "distribute", meaning: "분배하다" },
  { word: "diversify", meaning: "다양화하다" },
  { word: "eager", meaning: "열심인, 간절한" },
  { word: "elaborate", meaning: "정교한, 정성들인" },
  { word: "eliminate", meaning: "제거하다" },
  { word: "embrace", meaning: "포용하다, 껴안다" },
  { word: "emphasize", meaning: "강조하다" },
  { word: "endorse", meaning: "보증하다, 지지하다" },
  { word: "enrich", meaning: "무언가를 풍부하게 하다" },
  { word: "enthusiastic", meaning: "열정적인" },
  { word: "envious", meaning: "부러워하는, 질투하는" },
  { word: "equivalent", meaning: "동등한, 상당한" },
  { word: "erroneous", meaning: "잘못된" },
  { word: "evaluate", meaning: "평가하다" },
  { word: "exaggerate", meaning: "과장하다" },
  { word: "exceed", meaning: "넘다, 초과하다" },
  { word: "exemplify", meaning: "예증하다" },
  { word: "exert", meaning: "행사하다" },
  { word: "extend", meaning: "확장하다, 연장하다" },
  { word: "fathom", meaning: "깨닫다, 이해하다" },
  { word: "feasible", meaning: "실행 가능한" },
  { word: "fervent", meaning: "열렬한, 열정적인" },
  { word: "fluctuate", meaning: "변동하다" },
  { word: "forthcoming", meaning: "다가오는, 예정된" },
  { word: "frugal", meaning: "검소한, 절약하는" },
  { word: "fulfill", meaning: "이행하다, 만족시키다" },
  { word: "furthermore", meaning: "게다가, 더욱이" },
  { word: "generate", meaning: "생성하다, 발생시키다" },
  { word: "genuine", meaning: "진짜의, 진실된" },
  { word: "gratify", meaning: "만족시키다" },
  { word: "gregarious", meaning: "사교적인" },
  { word: "hence", meaning: "이로 인해, 그래서" },
  { word: "hesitant", meaning: "망설이는" },
  { word: "highlight", meaning: "강조하다" },
  { word: "hinder", meaning: "방해하다" },
  { word: "hypothesize", meaning: "가설을 세우다" },
  { word: "immense", meaning: "거대한, 막대한" },
  { word: "imminent", meaning: "임박한" },
  { word: "implement", meaning: "실행하다, 이행하다" },
  { word: "impose", meaning: "부과하다, 강요하다" },
  { word: "incentive", meaning: "동기, 장려" },
  { word: "inclusive", meaning: "포괄적인" },
  { word: "incur", meaning: "초래하다, 초래되다" },
  { word: "indicate", meaning: "나타내다, 가리키다" },
  { word: "indifferent", meaning: "무관심한, 냉담한" },
  { word: "inevitable", meaning: "불가피한" },
  { word: "inferior", meaning: "열등한, 못하는" },
  { word: "inflate", meaning: "팽창시키다" },
  { word: "ingenious", meaning: "독창적인, 기발한" },
  { word: "inquire", meaning: "조사하다, 문의하다" },
  { word: "inspect", meaning: "점검하다" },
  { word: "integrate", meaning: "통합하다, 통일하다" },
  { word: "interact", meaning: "상호작용하다" },
  { word: "interfere", meaning: "간섭하다, 방해하다" },
  { word: "intermediate", meaning: "중간의, 중급의" },
  { word: "intervene", meaning: "개입하다" },
  { word: "intricate", meaning: "복잡한, 얽힌" },
  { word: "intriguing", meaning: "흥미로운, 호기심을 자아내는" },
  { word: "invoke", meaning: "기원하다, 호소하다" },
  { word: "irrelevant", meaning: "관련없는" },
  { word: "jeopardize", meaning: "위태롭게 하다" },
  { word: "legitimate", meaning: "법적인, 정당한" },
  { word: "liberal", meaning: "자유로운, 관대한" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "mandatory", meaning: "의무적인, 필수적인" },
  { word: "manipulate", meaning: "조작하다, 다루다" },
  { word: "marginal", meaning: "여윽시의, 중요하지 않은" },
  { word: "mediate", meaning: "중재하다" },
  { word: "merge", meaning: "합병하다, 융합하다" },
  { word: "moderate", meaning: "적당한, 온건한" },
  { word: "modify", meaning: "수정하다, 변경하다" },
  { word: "multiply", meaning: "증가시키다, 곱하다" },
  { word: "negotiate", meaning: "협상하다" },
  { word: "nominal", meaning: "명목상의, 이름만의" },
  { word: "nurture", meaning: "양육하다, 기르다" },
  { word: "oblige", meaning: "강요하다, 의무를 지우다" },
  { word: "obsolute", meaning: "오래된, 쓸모없게 된" },
  { word: "obstruct", meaning: "막다, 방해하다" },
  { word: "omit", meaning: "빠뜨리다, 생략하다" },
  { word: "oppose", meaning: "반대하다, 대항하다" },
  { word: "opulent", meaning: "풍부한, 호화로운" },
  { word: "oversee", meaning: "감독하다" },
  { word: "overtake", meaning: "앞지르다, 따라잡다" },
  { word: "partial", meaning: "일부의, 부분적인" },
  { word: "perceive", meaning: "인식하다, 알아차리다" },
  { word: "perish", meaning: "멸망하다, 죽다" },
  { word: "pervade", meaning: "퍼지다, 스며들다" },
  { word: "pioneer", meaning: "개척자, 선구자" },
  { word: "plausible", meaning: "그럴듯한, 타당한" },
  { word: "ponder", meaning: "숙고하다, 곰곰히 생각하다" },
  { word: "prevalent", meaning: "만연하는, 흔한" },
  { word: "prior", meaning: "이전의, 우선하는" },
  { word: "proficient", meaning: "능숙한, 숙달한" },
  { word: "profound", meaning: "깊은, 심오한" },
  { word: "prohibit", meaning: "금지하다, 막다" },
  { word: "prolong", meaning: "연장하다" },
  { word: "prominent", meaning: "뛰어난, 유명한" },
  { word: "propose", meaning: "제안하다, 추천하다" },
  { word: "prosper", meaning: "번영하다" },
  { word: "provisional", meaning: "임시적인, 일시적인" },
  { word: "provoke", meaning: "자극하다, 화나게 하다" },
  { word: "punctual", meaning: "시간을 잘 지키는, 정시의" },
  { word: "purport", meaning: "의도하다, 의미하다" },
  { word: "pursue", meaning: "추구하다, 뒤쫓다" },
  { word: "qualify", meaning: "자격을 주다, 적격이 되다" },
  { word: "quench", meaning: "끄다, 만족시키다" },
  { word: "quote", meaning: "인용하다, 견적을 내다" },
  { word: "radiant", meaning: "빛나는, 환한" },
  { word: "ramification", meaning: "영향, 결과" },
  { word: "rational", meaning: "이성적인, 합리적인" },
  { word: "reap", meaning: "거두다, 수확하다" },
  { word: "recede", meaning: "물러나다, 줄어들다" },
  { word: "reconcile", meaning: "화해시키다, 조정하다" },
  { word: "redundant", meaning: "불필요한, 과잉의" },
  { word: "refute", meaning: "반박하다" },
  { word: "reinforce", meaning: "강화하다, 보강하다" },
  { word: "relinquish", meaning: "포기하다, 양도하다" },
  { word: "remedy", meaning: "치료하다, 해결하다" },
  { word: "render", meaning: "제공하다, 해주다" },
  { word: "renounce", meaning: "포기하다, 단념하다" },
  { word: "replenish", meaning: "보충하다, 다시 채우다" },
  { word: "repose", meaning: "쉬다, 안락하다" },
  { word: "repudiate", meaning: "부인하다, 거절하다" },
  { word: "reside", meaning: "거주하다" },
  { word: "resolute", meaning: "단호한, 결단력 있는" },
  { word: "resolve", meaning: "해결하다, 결정하다" },
  { word: "restore", meaning: "복구하다, 복원하다" },
  { word: "restrict", meaning: "제한하다, 한정하다" },
  { word: "retain", meaning: "보유하다, 유지하다" },
  { word: "retreat", meaning: "후퇴하다, 철수하다" },
  { word: "retrieve", meaning: "회수하다, 되찾다" },
  { word: "revoke", meaning: "철회하다, 폐지하다" },
  { word: "rigid", meaning: "단단한, 경직된" },
  { word: "robust", meaning: "튼튼한, 강건한" },
  { word: "rotate", meaning: "회전하다, 순환하다" },
  { word: "sanction", meaning: "제재, 승인" },
  { word: "saturate", meaning: "흠뻑 젖게 하다" },
  { word: "simplify", meaning: "간소화하다" },
  { word: "soothe", meaning: "진정시키다, 달래다" },
  { word: "speculate", meaning: "추측하다, 가정하다" },
  { word: "spontaneous", meaning: "자발적인, 자연적인" },
  { word: "stagnant", meaning: "침체된, 정체된" },
  { word: "stimulate", meaning: "자극하다, 격려하다" },
  { word: "strive", meaning: "노력하다, 애쓰다" },
  { word: "subside", meaning: "가라앉다, 진정되다" },
  { word: "substantiate", meaning: "입증하다, 뒷받침하다" },
  { word: "succinct", meaning: "간결한, 간명한" },
  { word: "suffice", meaning: "만족시키다, 충분하다" },
  { word: "suppress", meaning: "억제하다, 억압하다" },
  { word: "sustain", meaning: "지탱하다, 유지하다" },
  { word: "swift", meaning: "빠른, 신속한" },
  { word: "tedious", meaning: "지루한, 장황한" },
  { word: "terminate", meaning: "끝나다, 종료되다" },
  { word: "testify", meaning: "증언하다, 입증하다" },
  { word: "thrive", meaning: "번창하다, 번성하다" },
  { word: "tolerate", meaning: "견디다, 참다" },
  { word: "transform", meaning: "변형시키다, 변환하다" },
  { word: "transmit", meaning: "전송하다, 전달하다" },
  { word: "treasure", meaning: "소중히 하다, 보물" },
  { word: "undermine", meaning: "약화시키다, 손상시키다" },
  { word: "utilize", meaning: "이용하다, 활용하다" },
];

function engWordButton() {
  let engWord = $("#engWord");
  const randomNum = Math.floor(Math.random() * 210 + 1);
  engWord[0].innerHTML =
    wordList[randomNum - 1].word + "<br>" + wordList[randomNum - 1].meaning;
}
